/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module and_gate(g_input, e_input, o);
  input [3:0] e_input;
  input [3:0] g_input;
  output [3:0] o;
  XOR _0_ (
    .A(g_input[0]),
    .B(e_input[0]),
    .Z(o[0])
  );
  XOR _1_ (
    .A(g_input[1]),
    .B(e_input[1]),
    .Z(o[1])
  );
  XOR _2_ (
    .A(g_input[2]),
    .B(e_input[2]),
    .Z(o[2])
  );
  XOR _3_ (
    .A(g_input[3]),
    .B(e_input[3]),
    .Z(o[3])
  );
endmodule
