/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module and_gate(g_input, e_input, o);
  input e_input;
  input g_input;
  output o;
  AND _0_ (
    .A(g_input),
    .B(e_input),
    .Z(o)
  );
endmodule
